name: DigiteX

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env_file
    ports:
      - "5000:5000"
    image: digitex_backend:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    image: digitex_frontend:latest
