version: '3.8'

services:
  digitex-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    image: digitex:latest