name: Build and Deploy to Azure

on:
  push:
    branches: master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/digitex:latest .
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/digitex:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/digitex:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/digitex:${{ github.sha }}
        echo "Image pushed successfully!"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'digitex-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/digitex:latest