name: Build and Deploy DigiteX to Azure

on:
  push:
    branches:
      - ramitha

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/digitex-backend:latest ./backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/digitex-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/digitex-frontend:latest ./frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/digitex-frontend:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: digitex
          slot-name: production
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/digitex-frontend:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/digitex-backend:latest
