name: Build and Deploy DigiteX to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: digitex.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push images
        run: |
          docker-compose -f docker-compose.yml build
          docker tag digitex_backend:latest digitex.azurecr.io/digitex-backend:latest
          docker tag digitex_frontend:latest digitex.azurecr.io/digitex-frontend:latest
          docker push digitex.azurecr.io/digitex-backend:latest
          docker push digitex.azurecr.io/digitex-frontend:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: digitex
          slot-name: production
          images: |
            digitex.azurecr.io/digitex-frontend:latest
            digitex.azurecr.io/digitex-backend:latest
